#!/bin/bash

module --force purge

module load ncarenv/23.09
module load intel-classic/2023.2.1
module load ncarcompilers/1.0.0
module load cray-mpich/8.1.27
module load craype/2.7.23
module load netcdf-mpi/4.9.2
module load parallel-netcdf/1.12.3
module load udunits/2.2.28
module load ncview/2.1.9
module load mkl/2023.2.0

module list
